[workspace]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
platforms = ["linux-64", "osx-arm64"]
preview = ["pixi-build"]

[dependencies]
gen2d = { path = "packages/gen2d" }
mono = { path = "." }

[pypi-dependencies]

[tasks]

[package]
name = "mono"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[package.host-dependencies]
hatchling = "==1.26.3"
python = ">=3.11,<4.0"

[package.run-dependencies]
numpy = "<2.0.0"
