[project]
authors = [
    {name = "Mathieu Huot", email = "mathieu@chi-fro.org"},
]
dependencies = ["genjax"]
name = "gen2d"
requires-python = ">=3.11,<4.0"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
